# Generated by Django 6.0.7 on 2026-08-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejercicio',
            options={'ordering': ['nombre', 'tipo_equipo']},
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='tipo_equipo',
            field=models.CharField(choices=[('mancuerna', 'Mancuerna'), ('barra', 'Barra'), ('maquina', 'Máquina'), ('cable', 'Cable/Polea'), ('peso_corporal', 'Peso corporal'), ('kettlebell', 'Kettlebell'), ('banda', 'Banda de resistencia')], default='maquina', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rutinaejercicio',
            name='reps_objetivo',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AlterUniqueTogether(
            name='ejercicio',
            unique_together={('nombre', 'tipo_equipo')},
        ),
    ]
