# Generated by Django 6.0.7 on 2026-08-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_ejercicio_options_ejercicio_tipo_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='tipo_equipo',
            field=models.CharField(choices=[('mancuerna', 'Mancuerna'), ('barra', 'Barra'), ('maquina', 'Máquina'), ('cable', 'Cable'), ('peso_corporal', 'Peso corporal'), ('kettlebell', 'Kettlebell'), ('banda', 'Banda de resistencia')], max_length=20),
        ),
    ]
